server:
    port: 8084

spring:
  application:
    name: postservice

  datasource:
    url: jdbc:mysql://localhost:3313/db?serverTimezone=UTC
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

