server:
  port: 8088


spring:
  application:
    name: userservice
  datasource:
    url: jdbc:mysql://localhost:3314/db?serverTimezone=UTC
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/