insert into posts (id, title, user_id) values (1, 'Battle Royale (Batoru rowaiaru)', 1);
insert into posts (id, title, user_id) values (2, 'Matchmaker, The', 1);
insert into posts (id, title, user_id) values (3, 'Nightmare', 2);
insert into posts (id, title, user_id) values (4, 'Wyatt Earp''s Revenge', 2);
insert into posts (id, title, user_id) values (5, 'Dangerous Liaisons', 2);
insert into posts (id, title, user_id) values (6, 'Mahabharata, The', 2);
insert into posts (id, title, user_id) values (7, '2012: Time for Change', 3);
insert into posts (id, title, user_id) values (8, 'Jay-Z: Made in America', 3);
insert into posts (id, title, user_id) values (9, 'Misérables, Les', 3);
insert into posts (id, title, user_id) values (10, 'Streets of Fire', 3);
insert into posts (id, title, user_id) values (11, 'Day of the Doctor, The', 3);
insert into posts (id, title, user_id) values (12, 'Always Tell Your Wife', 3);
insert into posts (id, title, user_id) values (13, 'House That Dripped Blood, The', 13);
insert into posts (id, title, user_id) values (14, 'Steam Experiment, The', 14);
insert into posts (id, title, user_id) values (15, 'Felicia''s Journey', 15);
insert into posts (id, title, user_id) values (16, 'Winner, The', 16);
insert into posts (id, title, user_id) values (17, 'Hustler White', 17);
insert into posts (id, title, user_id) values (18, 'Night in Heaven, A', 18);
insert into posts (id, title, user_id) values (19, 'Robinson Crusoe (Adventures of Robinson Crusoe, The)', 19);
insert into posts (id, title, user_id) values (20, 'Oliver!', 20);
insert into posts (id, title, user_id) values (21, 'Grudge 2, The', 21);
insert into posts (id, title, user_id) values (22, 'Deathstalker II', 22);
insert into posts (id, title, user_id) values (23, 'Dallas: War of the Ewings', 23);
insert into posts (id, title, user_id) values (24, 'Lord, Save Us from Your Followers', 24);
insert into posts (id, title, user_id) values (25, 'Insidious: Chapter 2', 25);
insert into posts (id, title, user_id) values (26, 'Perfect Storm, The', 26);
insert into posts (id, title, user_id) values (27, 'It Came from Outer Space', 27);
insert into posts (id, title, user_id) values (28, 'Morgan Stewart''s Coming Home', 28);
insert into posts (id, title, user_id) values (29, 'Prince of the Sun: The Great Adventure of Horus (Taiyou no ouji Horusu no daibouken)', 29);
insert into posts (id, title, user_id) values (30, 'Fright to the Finish', 30);
insert into posts (id, title, user_id) values (31, 'Django the Bastard (Strangers Gundown, The) (Django il bastardo)', 31);
insert into posts (id, title, user_id) values (32, 'They', 32);
insert into posts (id, title, user_id) values (33, 'December 7th', 33);
insert into posts (id, title, user_id) values (34, 'Smoking/No Smoking', 34);
insert into posts (id, title, user_id) values (35, 'Apple Dumpling Gang, The', 35);
insert into posts (id, title, user_id) values (36, 'Before I Go to Sleep', 36);
insert into posts (id, title, user_id) values (37, 'Meet the Robinsons', 37);
insert into posts (id, title, user_id) values (38, 'Lot Like Love, A', 38);
insert into posts (id, title, user_id) values (39, 'Pinocchio', 39);
insert into posts (id, title, user_id) values (40, 'Ten Commandments, The', 40);